
<script type="text/javascript">
    if (window.ZipMoneyCheckoutWidgetModal == undefined) {
        var vInstanceName = 'window.ZipMoneyCheckoutWidgetModal';
        var vElementId = 'zipmoney-learn-more';
        var vDefaultContent = '<?php echo Mage::helper("zipmoneypayment/widget")->getDefaultContent(); ?>';
        var aPageContents = <?php echo json_encode(Mage::helper("zipmoneypayment/widget")->getCheckoutDialogPages()); ?>;

        try {
            window.ZipMoneyCheckoutWidgetModal = new WidgetModal(vInstanceName, vElementId, aPageContents, vDefaultContent);
        } catch (e) {
            if (typeof(window.ZipMoneyCheckoutWidgetModal) == 'undefined') {
                window.ZipMoneyCheckoutWidgetModal = {};
            }
            window.ZipMoneyCheckoutWidgetModal.showPopup = function() {alert('Sorry, can not load the content.')};
        }
    }
</script>

<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li class="form-alt"><?php echo $this->getRedirectMessage() ?></li>
    <?php if ($code = $this->getCreateBACode()): ?>
        <li class="form-alt">
            <label for="<?php echo $code; ?>"><input type="checkbox" id="<?php echo $code; ?>" value="1" name="payment[<?php echo $code; ?>]" class="checkbox" />
                <?php echo $this->__('Sign a billing agreement to streamline further purchases with zipMoney.') ?></label>

        </li>
    <?php endif; ?>
</ul>
