<?php
if ($this->isShow()):
    $this->getAssets();
    ?>
    <?php
    if (Mage::getStoreConfig('payment/zipmoney_developer_settings/jquery_enabled') == 1):
        ?>
        <script type="text/javascript" src="<?php echo $this->getSkinUrl('zipmoney/js/jquery-1.9.0.min.js') ?>"></script>
        <?php
    endif;
    if (Mage::getStoreConfig('payment/zipmoney_developer_settings/fancybox_enabled') == 1):
        ?>
        <script type="text/javascript" src="<?php echo $this->getSkinUrl('zipmoney/popup/fancybox/jquery.fancybox.js') ?>"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('zipmoney/popup/fancybox/jquery.fancybox.css') ?>" media="all" />
        <?php
    endif;
    ?>
    <script type="text/javascript">
        jQuery.noConflict();
        jQuery(document).ready(function() {
            jQuery(".fancybox").fancybox({
                'prevEffect': 'none',
                'nextEffect': 'none',
                'padding': 0
            });
        });
    </script>
    <div id="zipmoney-widget-specific-cart">
        <a class="fancybox fancybox.ajax" rel="widget-zip" data-fancybox-group="gallery" href="<?php echo Mage::getUrl('zipmoneypayment/popup/product_promotion_01/') ?>"> 
            <img src="<?php echo $this->assets_object->getPromotionUrl(); ?>"/>
        </a>
        <a class="fancybox fancybox.ajax" rel="widget-zip" style="display: none" data-fancybox-group="gallery" href="<?php echo Mage::getUrl('zipmoneypayment/popup/product_promotion_02/') ?>">&nbsp;</a>
    </div>

    <?php
endif;
?>