<?php if ($this->isShow()): ?>
<div id="zipmoney-top-strip-banner" class="zipmoney-strip-banner-responsive-top">
<?php echo $this->getChildHtml('zipmoneypayment.widget.banner.strip'); ?>
</div>

<script>
    Event.observe(window, 'load', function () {
        var verResponsive = '<?php echo $this->checkVersionResponsive()?>';
        if (verResponsive == 'false' || $$('.skip-links').length <= 0) {
            $('zipmoney-top-strip-banner').removeClassName('zipmoney-strip-banner-responsive-top');
        }
    });
</script>
<?php endif; ?>