<?php
/**
 * @category  Aligent
 * @package   zipmoney
 * @author    Andi Han <andi@aligent.com.au>
 * @copyright 2014 Aligent Consulting.
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      http://www.aligent.com.au/
 */
?>
<?php $buttonTitle = $this->__('zipMoney Express'); ?>

<script type="text/javascript">
    document.observe("dom:loaded", function() {
        var vElementId = 'zipmoney-widget-general';
        if (window.ZipMoneyWidgetModal == undefined) {
            var vInstanceName = 'window.ZipMoneyWidgetModal';
            var vDefaultContent = '<?php echo Mage::helper("zipmoneypayment/widget")->getDefaultContent(); ?>';
            var aPageContents = <?php echo json_encode(Mage::helper("zipmoneypayment/widget")->getAllTermsPages()); ?>;
            window.ZipMoneyWidgetModal = new WidgetModal(vInstanceName, vElementId, aPageContents, vDefaultContent);
            window.ZipMoneyWidgetModal.addListenerToMultipleElements('.zip-widget-general');
        }
    });
</script>

<div>
    <div id="zipmoney-express-cart" style="text-align:center">
        <span>-OR-</span>
        <div class="zipmoney-express-cart-button">
            <a id="zipmoney-express-button" class="zip-hover zip-express-button" href="<?php echo htmlentities($this->getExpressPaymentUrl()); ?>"  >
                <img id="zipmoney-express-button-img" class="zip-express-bt-img" src="<?php echo $this->getExpressButtonUrl(); ?>" alt="<?php echo $this->__('BUY NOW, PAY LATER'); ?>"/>
            </a>
        </div>
        <div class="zipmoney-express-cart-product-learn-more zip-widget-general" >
            <a id="zipmoney-express-learn-more" class="zip-hover zip-express-widget-link" style="font-family: Noto Sans; color: #808080; font-size: 11px;">
                <?php echo $this->getAdditionalText();?>
            </a>
        </div>
    </div>
    <span class="zip-cart-please-wait" id="redirecting-to-zipmoney" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Redirecting to zipMoney...') ?>" title="<?php echo $this->__('Redirecting to zipMoney...') ?>" class="v-middle" /> <?php echo $this->__('Redirecting to zipMoney...') ?>
    </span>
</div>

<script type="text/javascript">
    var vButtonId = 'zipmoney-express-button-img';
    var vLkSelector = '.zip-express-widget-link';
    window.ZipMoneyWidgetLink = new AdditionLink(vButtonId, vLkSelector);
    Event.observe(window, 'load', function () {window.ZipMoneyWidgetLink.adjustWidth();});
</script>

<?php if($this->_isIframeFlowEnabled()): ?>
    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            var parentElement = this;
            $$('.zip-express-button').each(function (oEle) {
                if (oEle == undefined) {
                    return;
                }

                oEle.observe('click', function (oEvent) {
                    oEvent.preventDefault();
                    showRedirectingText();
                    var vUrl = '<?php echo $this->getIframeRedirectUrl(); ?>';
                    var iframe = new iframeCheckout(vUrl, 'cart', '<?php echo $this->__('Can not redirect to zipMoney.') ?>');
                    iframe.redirectToCheckout();
                    Event.stop(oEvent);
                });
            });
        });

    </script>
<?php endif; ?>